Finally working

diff --git a/prognito b/prognito
--- a/prognito
+++ b/prognito
@@ -1,4 +1,9 @@
-#!/bin/bash
+
+test="$(pwd)"
+
+
+cd ~/Dokumenty/prognito || { echo "Directory not found"; exit 1; }
+
 if command -v python3 &>/dev/null; then
     echo "Running python script"
 else
@@ -6,4 +11,5 @@ else
     exit
 fi
 
-python main.py $@
+# Run the Python script with the directory argument
+python main.py "$@" -d "$test"
